/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.stone.dosql.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 06-09-2008
 * 
 * XDoclet definition:
 * @struts.form name="searchForm"
 */
public class SearchForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dbname property */
	private String dbname;

	/** selectString property */
	private String selectString;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
//        ActionErrors errors = new ActionErrors();
//        if(selectString == null || selectString.trim().length()==0)
//            errors.add("selectString",new ActionMessage("请输入查询语句",selectString));
//        return errors;
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.selectString="";
	}

	/** 
	 * Returns the dbname.
	 * @return String
	 */
	public String getDbname() {
		return dbname;
	}

	/** 
	 * Set the dbname.
	 * @param dbname The dbname to set
	 */
	public void setDbname(String dbname) {
		this.dbname = dbname;
	}

	/** 
	 * Returns the selectString.
	 * @return String
	 */
	public String getSelectString() {
		return selectString;
	}

	/** 
	 * Set the selectString.
	 * @param selectString The selectString to set
	 */
	public void setSelectString(String selectString) {
		this.selectString = selectString;
	}
}